// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl15cXvXV1qERcehQmySKmOmkSWr3VMvY',
    appId: '1:213033579428:web:c9fb1514da532371dd8731',
    messagingSenderId: '213033579428',
    projectId: 'redditclone-ad84b',
    authDomain: 'redditclone-ad84b.firebaseapp.com',
    storageBucket: 'redditclone-ad84b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CDIqZes1i3GyOWDZ6Ci_IPf6iJWAqCc',
    appId: '1:213033579428:android:c199862b7b324d19dd8731',
    messagingSenderId: '213033579428',
    projectId: 'redditclone-ad84b',
    storageBucket: 'redditclone-ad84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAtuNTyPaXSSqW3xdkzFQSArqMjJggEnY',
    appId: '1:213033579428:ios:ba5575c4004d9fbddd8731',
    messagingSenderId: '213033579428',
    projectId: 'redditclone-ad84b',
    storageBucket: 'redditclone-ad84b.appspot.com',
    iosClientId: '213033579428-ghbbsardvl3itsrss2tiomiacved8q0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
